<?php
//find the origin address
$http_origin = $_SERVER['HTTP_ORIGIN'];

if ($http_origin == "http://127.0.0.1")
{
	header("Access-Control-Allow-Origin: $http_origin");
}
//GET the data from the query form on the website
$name = $_GET['name'];
$email = $_GET['email'];
$message = $_GET['message'];

//check if any of the fields are empty
//if so, return to client and display error
if ($name == null){
echo "Enter your name";
}
else if($email == null){

echo "No contact email entered";
}

else if ($message == null){
echo "No message received";
}

else{
$host = 'localhost';
$username = 'root';
$password = '';
$db = 'test';

$con = mysqli_connect($host, $username, $password, $db);
if (!$con) {
    die('Could not connect: ' . mysqli_error($con));
}
try{
mysqli_select_db($con,"query");
$sql= "INSERT INTO query ( `query_id` , `username` , `query_message` )
VALUES (NULL ,'". $name . "', '". $message . "')";

$con->query($sql);
echo "Message has been received";
}
catch (Exception $e)
{
	echo $e->getMessage();
}
mysqli_close($con);
}
	//create filename
	//rather use a random function to create unique file name
	$my_file = "enquiries/". $name . "_enquiry.txt";
	//open file
	$handle = fopen($my_file , 'w') or die ("\nCannot create file: ".	$my_file);
	$string = "$name\n$email\nMessage:\n$message";
	fwrite($handle, $string);
	
	//mail enquiry to mail server and to user
	try{
	$msg = "Received from: " . $name . "\nEmail: " . $email . "\n\n$message\n\n";
	$subject = "Enquiry - " . $name;
	$msg = wordwrap($msg,70);
	
	$receiver = $email;
	$automsg = "--------------------------------------------------\n" . "Message
	automatically generated by the site\nDo not reply to this email.";
	$msg = $msg . $automsg;
	mail($receiver, $subject, $msg);
	}	

	catch(Exception $e){
	echo 'Error: ' . $e->getMessage();
	}

?>
